### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by matkuki** [elcritch/fidgetty#9]
Hi,

wondering what is your time-plan for this project to be semi-production ready?
Is it just a hobby or are there bigger plans?
I'm willing to help, if it will speed things up. Testing, feedback, whatever you need.

Thanks

**Comment by elcritch** [comment]
Hey! I figure the library itself could be ready for a beta status in a 2-3 months, maybe sooner with help. Though it'd be useable for semi-production apps sooner. I'm not planning any big api changes unless there's big issues blocking something. The core features are there now, but there's a fair bit of testing, documentation, and shoring up todo.

Things like: 
- text selection is disabled/broken after a refactor but should be easy to enable again
- the css grid works but only for horizontal auto-placement, etc. 
  + I'm pretty excited by how well css-grid works (!!) though it still has a bit of work to shore up (see [cssgrid](https://github.com/elcritch/cssgrid)). 
- theming needs to be used and vetted that it's useable.
- need to add basic layout's like split-pane (using css grid).
- I'd really like to switch all the box / ui coordinates to using constraints if possible

Currently this is a hobby project. However, it does seem cool things could come from it! I've wanted a compiled but easy-to-use UI for a long time. I think others feel the same and perhaps there's a market for something along those lines?

It'd be great to get some help. The best would be trying to build sample apps and giving feedback or tweaking the API would be awesome. I've starting building some apps with it myself and already found a number of small issues. 

Anything of those interest you? Also hit me up on the Nim Discord too.

**Comment by elcritch** [comment]
P.S. if you start building an example app you could just start filing issues as you run into them. No need for anything fancy at this point.

**Comment by matkuki** [comment]
Very good, thank you 👍👍
Will start testing this week.
